### ISSUE TITLE
remove use of __proto__

### ISSUE THREAD

**Issue by nitsky** [acornjs/acorn-private-class-elements#13]
Hi, node recently added a `--disable-proto` option to disable use of `__proto__` due to security issues: https://github.com/nodejs/node/pull/32279. Similarly, deno also recently removed support for `__proto__`: https://github.com/denoland/deno/pull/4341. Would you consider removing the use of `__proto__` in this package? The changes proposed in https://github.com/acornjs/acorn-private-class-elements/pull/10 would take care of it if merged.

**Comment by adrianheine** [comment]
Using `Object.getPrototypeOf` if available should be a viable workaround.
