### ISSUE TITLE
Keyword support

### ISSUE THREAD

**Issue by guybedford** [acornjs/acorn-private-class-elements#14]
The following throws an error:

```js
class P {
  delete = 5;
}
```

with the above is supported in eg Babel. Yet the corresponding class method definition is fine:

```js
class P {
  delete () {
  }
}
```

I wonder if we should run the `parseIdentifier` with `liberal` to cater to this flexibility? I'm not sure which would be exactly correct by the spec, but I feel like it likely would be similar to class definitions surely?

**Comment by adrianheine** [comment]
That's fixed with acornjs/acorn-class-fields#10, right?
